config/routes.rb
Rails.application.routes.draw do

  # action groups
  resources :action_groups, path: 'aktionsgruppen'
  get ':id/aktionen', to: 'action_groups#show', as: 'show_action_group'


  # actions & events
  resources :actions, path: 'aktionen' do
    member do
      delete :delete_leader
      get :make_visible
      get :make_invisible
      get :crop_picture
      post :contact_volunteers
      post :contact_leaders
      get :clone
    end
  end
  resources :events do
    member do
      get :enter
      get :leave
      get :register_for_participation
      delete :delete_volunteer
    end
  end


  # news entries
  resources :news_entries, path: 'news' do
    member do
      get :crop_picture
    end
  end


  # galleries
  resources :galleries do
    member do
      get :make_all_visible
      get :make_all_invisible
    end
  end
  resources :gallery_pictures do
    member do
      get :make_visible
      get :make_invisible
    end
  end


  # users & user roles
  devise_for :users, path: '',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'edit_password'},
             controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :roles, except: [:show]
  resources :users, except: [:new, :create] do
    member do
      get :confirm_delete
      post :contact_user
    end
  end
  get :unsubscribe, to: 'users#unsubscribe'


  # surveys
  scope module: 'surveys' do
    resources :templates, as: :surveys_templates, path: 'umfragen' do
      resources :submissions, as: :surveys_submissions, path: 'antworten'
    end
  end


  # messages
  post 'kontakt', to: 'messages#send_contact_mail', as: 'send_contact_mail'
  resources :orga_messages, path: 'orga-mails' do
    member do
      get :send_message
    end
  end


  # statistics
  get 'statistiken/teilnahmen', to: 'statistics#participations'
  get 'statistiken/teilnahmen/:date', to: 'statistics#participations_on_day', as: :participations_on_day
  get 'statistiken/auslastung', to: 'statistics#occupancy'
  get 'statistiken/auslastung-:title', to: 'statistics#occupancy', as: :occupancy_in_year


  # pages
  root 'pages#home'
  get '/kontakt', to: 'pages#contact', as: :contact
  get '/eigene-aktion', to: 'pages#own_action', as: :own_action
  get '/:page', to: 'pages#page', as: :show_page


  # iCal
  get 'ical/aktionen/:action_id.ics', to: 'ical#actions', as: :action_ical
  get 'ical/aktionswochen/:action_group_id.ics', to: 'ical#action_groups', as: :action_group_ical
  get 'ical/users/:ical_token/:user_id.ics', to: 'ical#users', as: :user_ical
  get 'ical/aktionen.ics', to: 'ical#all_actions', as: :all_actions_ical


  # API
  namespace :api, constraints: { format: 'json' } do
    jsonapi_resources :action_groups
    jsonapi_resources :actions
    jsonapi_resources :events
    jsonapi_resources :news_entries
    jsonapi_resources :users
    jsonapi_resources :galleries

    jsonapi_resources :gallery_pictures do
      member do
        get :rotateRight
        get :rotateLeft
      end
    end

    scope module: 'surveys' do
      resources :templates, as: :surveys_templates, path: 'umfragen' do
        resources :submissions, as: :surveys_submissions, path: 'antworten'
      end
    end

  end

end

app/models/action_group.rb
class ActionGroup < ApplicationRecord
  validates_uniqueness_of :title

  has_many :actions

  validates_presence_of :start_date, :end_date
  enum declination: [:m_sg, :m_pl, :f_sg, :f_pl]

  scope :default, -> { where(default: true).first }
  scope :upcoming, -> { where('end_date >= ?', Date.current).order(:start_date) }
  scope :newest, -> { order(start_date: :desc) }

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def active_user_count
    # TODO: this is still slow
    User.left_outer_joins(:actions_as_leader, events_as_volunteer: :initiative)
        .where('actions.visible OR initiatives_events.visible')
        .where('actions.action_group_id = ? OR initiatives_events.action_group_id = ?', self.id, self.id)
        .distinct.count
  end

  def vacancy_count
    actions.visible.upcoming.sum(&:available_places)
  end

  def date_range
    start_date..end_date
  end

  private

  def should_generate_new_friendly_id?
    title_changed? || super
  end

  def slug_candidates
    candidates = []
    candidates << [title]
    candidates << [title, start_date.year]
    candidates
  end
end

app/controllers/action_groups_controller.rb
class ActionGroupsController < ApplicationController
  before_action :set_action_group, except: [:index, :new, :create]
  before_action :authenticate_admin!, except: [:show]
  before_action :authorize_action_group, except: [:index, :new, :create]

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  respond_to :html

  def index
    @action_groups = policy_scope(ActionGroup.all)
  end

  def show
    @actions = policy_scope(@action_group.actions.toplevel)
                   .order(visible: :desc, picture_source: :desc)
                   .includes(:events, subactions: :events)

    if params[:filter]
      p = filter_params
      @actions = @actions.where(visible: (p[:visibility] != 'hidden')) unless p[:visibility].blank?

      unless p[:day].blank? || !p[:day].match(/\A\d{2,4}-\d{1,2}-\d{1,2}\z/)
        date = Date.parse(p[:day])
        @actions = @actions.left_outer_joins(:events, subactions: [:events])
                       .where('events.date = ? OR events_actions.date = ?', date, date).distinct
      end

      @actions = @actions.select { |a| a.start_time && a.start_time.hour >= 17 } if p[:after_17h] == '1'
    end

  end

  def new
    @action_group = ActionGroup.new
    authorize_action_group
  end

  def edit
  end

  def create
    @action_group = ActionGroup.new(action_group_params)
    authorize_action_group
    @action_group.save
    respond_with @action_group
  end

  def update
    @action_group.update(action_group_params)
    respond_with @action_group
  end

  def destroy
    @action_group.destroy
    respond_with @action_group
  end

  private

  def set_action_group
    @action_group = ActionGroup.friendly.find(params[:id])
    not_found unless @action_group
  end

  def action_group_params
    params.require(:action_group).permit(:title, :default, :start_date, :end_date, :declination)
  end

  def filter_params
    params.require(:filter).permit(:visibility, :day, :after_17h)
  end

  def authorize_action_group
    authorize @action_group
  end
end

app/controllers/api/action_groups_controller.rb
class Api::ActionGroupsController < Api::ApiController

  include JSONAPI::ActsAsResourceController

  private

  def context
    { user: current_user }
  end
end

app/helpers/action_groups_helper.rb
module ActionGroupsHelper

  # Gives a list of all days (date + label) within the action group
  def options_for_day_select(action_group)
    action_groups = [action_group].flatten
    dates = action_groups.collect{ |group| group.date_range.to_a }.flatten
    format = :short_with_weekday
    format = :weekday_and_year if action_groups.count > 1
    dates.map{ |date| [I18n.l(date, format: format), date.strftime("%F")]}
  end

  # Splits the action group title, separating a possible "Aktionswoche" or "Aktionstag" prefix
  def split_action_group_type_prefix(title)
    temp_title = title.dup
    return temp_title.slice!(/Aktionswoche|Aktionstag/), temp_title.strip
  end

  # Gives the (chronologically) previous and next action groups
  def get_connected_action_groups(action_group)
    groups = ActionGroup.all.order(:start_date)
    group_index = groups.index(action_group)
    previous_group = group_index.positive? ? groups[group_index - 1] : nil
    next_group = groups[group_index + 1]
    return previous_group, next_group
  end

  # Gives the correct preposition for the group title (or date) depending on usage
  def action_group_declination(action_group, usage)
    is_day = (action_group.start_date == action_group.end_date)
    case usage
    when :temporal
      t('general.declination.' + (is_day ? 'at.' : 'in.')  + action_group.declination)
    when :nominative
      t('general.declination.the.' + action_group.declination)
    when :date_range
      t('general.declination.' + (is_day ? 'at.m_sg' : 'from.m_sg'))
    end
  end

  # Smartly formats and localizes a date range
  def date_range(from_date, until_date, options = {})
    options.symbolize_keys!
    format = options[:format] || :short
    separator = options[:separator] || "-"

    if format.to_sym == :short
      month_names = I18n.t("date.abbr_month_names")
    else
      month_names = I18n.t("date.month_names")
    end

    from_day = from_date.day
    from_month = month_names[from_date.month]
    from_year = from_date.year
    until_day = until_date.day

    dates = { from_day: from_day }

    if from_date.day == until_date.day && from_date.month == until_date.month && from_date.year == until_date.year
      date_format = "same_day"
      dates.merge!(day: from_day, month: from_month, year: from_year)
    elsif from_date.month == until_date.month && from_date.year == until_date.year
      date_format = "same_month"
      dates.merge!(until_day: until_day, month: from_month, year: from_year)
    else
      until_month = month_names[until_date.month]

      dates.merge!(from_month: from_month, until_month: until_month, until_day: until_day)

      if from_date.year == until_date.year
        date_format = "different_months_same_year"
        dates.merge!(year: from_year)
      else
        until_year = until_date.year

        date_format = "different_years"
        dates.merge!(from_year: from_year, until_year: until_year)
      end
    end

    I18n.t("date_range.#{format}.#{date_format}", dates.merge(sep: separator))
  end

end

app/views/action_groups/_form.erb
<%= form_with model: @action_group, local: true do |f| %>
  <% if @action_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@action_group.errors.count, "error") %> prohibited this action group from being saved:</h2>

      <ul>
      <% @action_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :default %><br>
    <%= f.check_box :default %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.text_field(:start_date, value: @action_group.start_date ? l(@action_group.start_date, format: :numeric) : '',
                     data: { 'behaviour': 'datepicker' }) %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.text_field(:end_date, value: @action_group.end_date ? l(@action_group.end_date, format: :numeric) : '',
                     data: { 'behaviour': 'datepicker' }) %>
  </div>
  <div class="field">
    <%= f.label :declination %><br>
    <%= f.select :declination, enum_options_for_select(ActionGroup, :declination) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/action_groups/edit.erb
<h1>Editing action_group</h1>
<%= render 'form' %>

<%= link_to 'Show', @action_group %> |
<%= link_to 'Back', action_group_path %>

app/views/action_groups/index.erb
<h1>Listing action_groups</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Default</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @action_groups.each do |action_group| %>
      <tr>
        <td><%= action_group.title %></td>
        <td><%= action_group.default %></td>
        <td><%= link_to 'Show', show_action_group_path(action_group) %></td>
        <td><%= link_to 'Edit', edit_action_group_path(action_group) %></td>
        <td><%= link_to 'Destroy', action_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New action group', new_action_group_path %>

app/views/action_groups/new.erb
<h1>New action group</h1>
<%= render 'form' %>
<%= link_to 'Back', action_groups_path %>

app/views/action_groups/show.erb
<% provide :title, @action_group.title %>
<% wrapper_set %>
<% actions = policy_scope(@action_group.actions.toplevel) %>
<% date_range_str = date_range(@action_group.start_date, @action_group.end_date, format: :long) %>

<% content_for :head do %>
  <% desc_date = action_group_declination(@action_group, :date_range).sub(/^./, &:upcase) + ' ' + date_range_str %>
  <% desc = t('action_group.help.description', date: desc_date,
              action_group: action_group_declination(@action_group, :nominative) + ' ' + @action_group.title) %>
  <meta name="description" content="<%= strip_tags desc %>" />
  <meta property="og:image" content="https://www.servethecity-karlsruhe.de/images/share.jpg" />
  <meta property="og:description" content="<%= strip_tags desc %>" />
<% end %>



<div id="action-group-header" class="white-box px-2 py-4">
  <% previous_group, next_group = get_connected_action_groups(@action_group) %>
  <div class="row align-items-center">
    <div class="col-6 col-sm-3 order-first">
      <% if previous_group %>
        <% type, name = split_action_group_type_prefix(previous_group.title) %>
        <%= link_to show_action_group_path(previous_group) do %>
          <div class="fas fa-2x fa-chevron-left pr-2"></div>
          <div class="neighbor-linktext">
            <div class="type"><%= type %></div>
            <div class="title"><%= name %></div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-6 col-sm-3 order-last">
      <% if next_group %>
        <% type, name = split_action_group_type_prefix(next_group.title) %>
        <%= link_to show_action_group_path(next_group) do %>
          <div class="neighbor-linktext">
            <div class="type"><%= type %></div>
            <div class="title"><%= name %></div>
          </div>
          <div class="fas fa-2x fa-chevron-right pl-2"></div>
        <% end %>
      <% end %>
    </div>
    <div class="col-sm-6 text-center title">
      <h1 class="m-0"><%= @action_group.title %></h1>
      <div class="date h3 m-0"><%= date_range_str %></div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-3 col-lg-2">
    <div class="row align-items-stretch">

      <%# general info %>
      <div id="action-group-info" class="col-sm-6 col-md-12">
        <div class="white-box">
          <%# total action count %>
          <div class="infobox">
            <span>
              <%= actions_count = actions.visible.count %>
              <% if (hidden_actions_count = actions.hidden.count) > 0 %>
                <span class="hidden-actions">+  <%= hidden_actions_count.to_s %></span>
              <% end %>
            </span>
            <div><%= Action.model_name.human(count: actions_count) %></div>
          </div>

          <%# total unique user count %>
          <% if @action_group.active_user_count > 0 %>
            <% if current_user&.in_orga_team? %>
              <a href="<%= statistiken_teilnahmen_path %>">
            <% end %>
            <div class="infobox">
              <span><%= @action_group.active_user_count %></span>
              <div><%= t('action_group.info.volunteers') %></div>
            </div>
            <% if current_user&.in_orga_team? %>
              </a>
            <% end %>
          <% end %>

          <%# total free places count %>
          <% if (vacancy_count = @action_group.vacancy_count) > 0 %>
            <% if current_user&.in_orga_team? %>
              <a href="<%= statistiken_auslastung_path %>">
            <% end %>
            <div class="infobox">
              <span><%= vacancy_count %></span>
              <div><%= t('action_group.info.vacancies') %></div>
            </div>
            <% if current_user&.in_orga_team? %>
              </a>
            <% end %>
          <% end %>
        </div>
      </div>

      <%# filter module %>
      <div class="col-sm-6 col-md-12">
        <div class="white-box">
          <h3><%= t 'action_group.heading.filter' %></h3>
          <%= bootstrap_form_for(:filter, url: actions_path, method:'get', html: {data: {
                class: 'ActionFilter', list: '#action-list', info: '#action-group-filter-results'}}) do |f| %>
            <%= f.select(:day, options_for_day_select(@action_group), include_blank: t('action_group.form.day_filter_blank'), hide_label: true) %>
            <%= f.check_box :after_17h, label: t('action_group.form.actionsAfter5pm') %>
            <%= f.submit t('action_group.button.filter'), class:'btn btn-secondary btn-block' %>
          <% end %>
        </div>
      </div>

      <%# propose action link %>
      <div class="col-sm-6 col-md-12 hidden-xs-down">
        <div class="white-box">
          <h3>Eigene Aktion</h3>
          <span><%= t('action_group.help.wantToStartOwnAction') %></span>
          <%= link_to t('action_group.help.weHelpYou'), own_action_path %>
        </div>
      </div>

      <%# admin options %>
      <% if policy(:action).new? %>
        <div class="col-sm-6 col-md-12 hidden-xs-down">
          <div class="white-box">
            <h3>Optionen</h3>
            <%= link_to t('action_group.button.newAction'), new_action_path, class:'btn btn-secondary btn-block' %>
          </div>
        </div>
      <% end %>

    </div>
  </div>
  <div class="col-md-9 col-lg-10">

    <div id="action-list">
      <%= render '/actions/action_card_list', actions: @actions %>
      <% unless actions.any? %>
        <div class="white-box text-center" style="max-width: 600px; margin: 30px">
          <%= t('action_group.info.noActions') %>
        </div>
      <% end %>
    </div>

  </div>
</div>

<div class="white-box hidden-sm-up">
  <h3>Eigene Aktion</h3>
  <span><%= t('action_group.help.wantToStartOwnAction') %></span>
  <%= link_to t('action_group.help.weHelpYou'), own_action_path, class:'btn btn-secondary btn-new-action' %>
</div>

<% if policy(:action).new? %>
  <div class="white-box hidden-sm-up">
    <h3>Optionen</h3>
    <%= link_to t('action_group.button.newAction'), new_action_path, class:'btn btn-secondary btn-block' %>
  </div>
<% end %>