config/routes.rb
Rails.application.routes.draw do

  # action groups
  resources :action_groups, path: 'aktionsgruppen'
  get ':id/aktionen', to: 'action_groups#show', as: 'show_action_group'


  # actions & events
  resources :actions, path: 'aktionen' do
    member do
      delete :delete_leader
      get :make_visible
      get :make_invisible
      get :crop_picture
      post :contact_volunteers
      post :contact_leaders
      get :clone
    end
  end
  resources :events do
    member do
      get :enter
      get :leave
      get :register_for_participation
      delete :delete_volunteer
    end
  end


  # news entries
  resources :news_entries, path: 'news' do
    member do
      get :crop_picture
    end
  end


  # galleries
  resources :galleries do
    member do
      get :make_all_visible
      get :make_all_invisible
    end
  end
  resources :gallery_pictures do
    member do
      get :make_visible
      get :make_invisible
    end
  end


  # users & user roles
  devise_for :users, path: '',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'edit_password'},
             controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :roles, except: [:show]
  resources :users, except: [:new, :create] do
    member do
      get :confirm_delete
      post :contact_user
    end
  end
  get :unsubscribe, to: 'users#unsubscribe'


  # surveys
  scope module: 'surveys' do
    resources :templates, as: :surveys_templates, path: 'umfragen' do
      resources :submissions, as: :surveys_submissions, path: 'antworten'
    end
  end


  # messages
  post 'kontakt', to: 'messages#send_contact_mail', as: 'send_contact_mail'
  resources :orga_messages, path: 'orga-mails' do
    member do
      get :send_message
    end
  end


  # statistics
  get 'statistiken/teilnahmen', to: 'statistics#participations'
  get 'statistiken/teilnahmen/:date', to: 'statistics#participations_on_day', as: :participations_on_day
  get 'statistiken/auslastung', to: 'statistics#occupancy'
  get 'statistiken/auslastung-:title', to: 'statistics#occupancy', as: :occupancy_in_year


  # pages
  root 'pages#home'
  get '/kontakt', to: 'pages#contact', as: :contact
  get '/eigene-aktion', to: 'pages#own_action', as: :own_action
  get '/:page', to: 'pages#page', as: :show_page


  # iCal
  get 'ical/aktionen/:action_id.ics', to: 'ical#actions', as: :action_ical
  get 'ical/aktionswochen/:action_group_id.ics', to: 'ical#action_groups', as: :action_group_ical
  get 'ical/users/:ical_token/:user_id.ics', to: 'ical#users', as: :user_ical
  get 'ical/aktionen.ics', to: 'ical#all_actions', as: :all_actions_ical


  # API
  namespace :api, constraints: { format: 'json' } do
    jsonapi_resources :action_groups
    jsonapi_resources :actions
    jsonapi_resources :events
    jsonapi_resources :news_entries
    jsonapi_resources :users
    jsonapi_resources :galleries

    jsonapi_resources :gallery_pictures do
      member do
        get :rotateRight
        get :rotateLeft
      end
    end

    scope module: 'surveys' do
      resources :templates, as: :surveys_templates, path: 'umfragen' do
        resources :submissions, as: :surveys_submissions, path: 'antworten'
      end
    end

  end

end

app/models/surveys.rb
module Surveys
  def self.table_name_prefix
    'surveys_'
  end
end

app/models/surveys/answer.rb
class Surveys::Answer < ApplicationRecord

  belongs_to :question, class_name: 'Surveys::Question'
  belongs_to :submission, class_name: 'Surveys::Submission'

  default_scope {joins(:question).order('surveys_questions.position')}
end

app/models/surveys/question.rb
class Surveys::Question < ApplicationRecord

  belongs_to :template, class_name: 'Surveys::Template'
  has_many :answers, class_name: 'Surveys::Answer', dependent: :destroy

  enum question_type: { text: 1, choice: 2, choice_or_text: 3, text_line: 4, info: 5 }

end

app/models/surveys/submission.rb
class Surveys::Submission < ApplicationRecord

  belongs_to :template, class_name: 'Surveys::Template'
  has_many :answers, class_name: 'Surveys::Answer', dependent: :destroy
  accepts_nested_attributes_for :answers

  def self.create_for_template template
    submission = new
    submission.template = template
    template.questions.each do |question|
      submission.answers.build(question: question)
    end
    submission
  end

end

app/models/surveys/template.rb
class Surveys::Template < ApplicationRecord

  has_many :questions, -> { order 'position' }, class_name: 'Surveys::Question', dependent: :destroy
  has_many :submissions, :class_name => 'Surveys::Submission', dependent: :destroy
  accepts_nested_attributes_for :questions, reject_if: lambda { |a| a[:text].blank? }, allow_destroy: true

  extend FriendlyId
  friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    title_changed? || super
  end

end

app/controllers/api/surveys/submissions_controller.rb
class Api::Surveys::SubmissionsController < Api::ApiController

  acts_as_token_authentication_handler_for User, except: [:show]

  after_action :verify_authorized

  def create
    @submission = Surveys::Submission.new(submission_params)
    authorize @submission
    @submission.user_id = current_user.id if current_user && @submission.template.show_in_user_profile
    @submission.save
    respond_with :api, @submission.template, @submission
  end

  private

  def submission_params
    params.require(:surveys_submission).permit(:template_id, answers_attributes: [:id, :question_id, :text])
  end

end

app/controllers/surveys/submissions_controller.rb
class Surveys::SubmissionsController < ApplicationController
  before_action :authenticate_admin_or_coordinator!, except: [:new, :create]
  before_action :set_submission, only: [:show, :edit, :update, :destroy]
  before_action :authorize_submission, except: [:index, :new, :create]

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  respond_to :html

  def index
    @template = Surveys::Template.friendly.find(params[:surveys_template_id])
    @submissions = policy_scope(@template.submissions.order(created_at: :desc))
  end

  def show
    respond_with(@submission)
  end

  def new
    template = Surveys::Template.friendly.find(params[:surveys_template_id])
    @submission = Surveys::Submission.create_for_template(template)
    authorize_submission
    respond_with(@submission)
  end

  def edit
  end

  def create
    @submission = Surveys::Submission.new(submission_params)
    @submission.user_id = current_user.id if current_user && @submission.template.show_in_user_profile
    authorize_submission
    @submission.save
    redirect_to '/', notice: t('surveys.message.answerCreated')
  end

  def update
    @submission.update(submission_params)
    respond_with(@submission)
  end

  def destroy
    @submission.destroy
    respond_with(@submission)
  end

  private

  def set_submission
    @submission = Surveys::Submission.find(params[:id])
  end

  def submission_params
    params.require(:surveys_submission).permit(:template_id, answers_attributes: [:id, :question_id, :text])
  end

  def authorize_submission
    authorize @submission
  end
end

app/controllers/surveys/templates_controller.rb
class Surveys::TemplatesController < ApplicationController
  before_action :authenticate_admin_or_coordinator!, except: :show
  before_action :set_template, only: [:show, :edit, :update, :destroy]
  before_action :redirect_non_admins_to_answers, only: :show
  before_action :authorize_template, except: [:index, :new, :create]

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  respond_to :html

  def index
    @templates = policy_scope(Surveys::Template)
    respond_with(@templates)
  end

  def show
    respond_with(@template)
  end

  def new
    @template = Surveys::Template.new
    @template.questions.build
    authorize_template
    respond_with(@template)
  end

  def edit
  end

  def create
    @template = Surveys::Template.new(template_params)
    authorize_template
    @template.save
    respond_with(@template)
  end

  def update
    @template.update(template_params)
    respond_with(@template)
  end

  def destroy
    @template.destroy
    respond_with(@template)
  end

  private

  def set_template
    @template = Surveys::Template.friendly.find(params[:id])
  end

  def template_params
    params.require(:surveys_template).permit(:title, :show_in_user_profile, questions_attributes:
        [:id, :text, :explanation, :answer_options, :question_type, :position, :is_subquestion, :_destroy] )
  end

  def authorize_template
    authorize @template
  end

  def redirect_non_admins_to_answers
    unless current_user && (current_user.admin? || current_user.coordinator?)
      redirect_to new_surveys_template_surveys_submission_path(@template)
    end
  end
end

app/helpers/surveys/answers_helper.rb
module Surveys::AnswersHelper
end

app/helpers/surveys/questions_helper.rb
module Surveys::QuestionsHelper
end

app/helpers/surveys/submissions_helper.rb
module Surveys::SubmissionsHelper
end

app/helpers/surveys/templates_helper.rb
module Surveys::TemplatesHelper
end

app/views/surveys/templates/_form.erb
<%= bootstrap_form_for(@template) do |f| %>

<% if @template.errors.any? %>
  <section id="error_explanation">
    <h2><%= t('surveys.message.errorList') %></h2>
    <ul>
      <% @template.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
  </section>
<% end %>

<div class="record-header">
  <div class="type">
    &nbsp;<%= isNew ? t('surveys.heading.newTemplate') : t('surveys.heading.editTemplate') %>&nbsp;
  </div>
  <h1><%= @template.title %></h1>
</div>


<section>
  <%= f.text_field :title %>
  <%= f.check_box :show_in_user_profile %>
</section>

<div class="questions" data-class="DynamicFormList">
  <div class="prototype d-none">
    <% new_object = f.object.class.reflect_on_association(:questions).klass.new %>
    <%= f.fields_for(:questions, new_object, child_index: :new_item) do |builder|
      render('question_fields', f: builder)
    end %>
  </div>
  <%= f.fields_for :questions do |builder| %>
    <%= render 'question_fields', f: builder %>
  <% end %>
  <%= link_to t('surveys.button.addQuestion'), 'javascript:void(0);', class: 'add-link btn btn-secondary' %>
</div>

<section>
  <%= f.submit t('surveys.button.saveTemplate'), class: 'btn btn-primary' %>
  <%= link_to t('surveys.navigation.toTemplateOverview'), surveys_templates_path, class: 'btn btn-secondary' %>
  <% if !isNew %>
    <%= link_to t('surveys.button.deleteTemplate'), surveys_template_path(@template), method: :delete,
                data: { confirm: t('general.message.confirmDelete') }, class: 'btn btn-secondary' %>
  <% end %>
</section>

<% end %>

app/views/surveys/templates/_question_fields.erb
<section class="item">
  <div class="row">
    <div class="col-sm-6">
      <%= f.hidden_field :position, class: 'position-field' %>
      <%= f.text_area :text %>
      <%= f.select(:question_type, Surveys::Question.question_types.keys.map {
            |s| [t("surveys.question.type.#{s}"), s] }) %>
      <%= f.check_box :is_subquestion %>
    </div>
    <div class="col-sm-6">
      <%= f.text_area :explanation %>
      <%= f.text_area :answer_options %>
      <%= f.hidden_field :_destroy %>
      <%= link_to t('surveys.button.removeQuestion'), "javascript:void(0);",
                  class: 'remove-link btn btn-secondary' %>
    </div>
  </div>
</section>

app/views/surveys/templates/edit.erb
<% provide :title, t('layout.title.templateEdit', template:@template.title) %>

<%= render 'form', isNew: false %>

app/views/surveys/templates/index.erb
<% provide :title, t('layout.title.templateList') %>

<h1><%= t('surveys.heading.templateList') %></h1>

<ul>
  <% @templates.each do |template| %>
    <li>
      <%= link_to template.title, template %>
    </li>
  <% end %>
</ul>

<br>

<%= link_to t('surveys.button.newTemplate'), new_surveys_template_path, class: 'btn btn-secondary' %>

app/views/surveys/templates/new.erb
<% provide :title, t('layout.title.templateNew') %>

<%= render 'form', isNew: true %>

app/views/surveys/templates/show.erb
<% provide :title, t('layout.title.templateView', template: @template.title) %>

<p id="notice"><%= notice %></p>

<div class="record-header">
  <div class="type">
    &nbsp;<%= Surveys::Template.model_name.human %>&nbsp;
  </div>
  <h1><%= @template.title %></h1>
</div>

<% idx = 0 %>
<% @template.questions.each do |question| %>

  <% question_label = question.text %>
  <% if !question.is_subquestion %>
      <% idx += 1 %>
      <% question_label = idx.to_s + '.) ' + question_label %>
  <% end %>

  <div class="<%= question.is_subquestion ? 'subquestion' : '' %>">
    <h3><%= question_label %></h3>
    <%= content_tag(:p, question.explanation, class: 'explanation') unless question.explanation.blank? %>
    <p><%= question.answer_options %></p>
  </div>
<% end %>

<div class="section">
  <%= link_to t('surveys.button.editTemplate'), edit_surveys_template_path(@template), class: 'btn btn-secondary' %>
  <%= link_to t('surveys.navigation.toTemplateOverview'), surveys_templates_path, class: 'btn btn-secondary'%>
  <%= link_to t('surveys.button.newSubmission'), new_surveys_template_surveys_submission_path(@template), class: 'btn btn-secondary'%>
  <%= link_to t('surveys.button.showSubmissions'), surveys_template_surveys_submissions_path(@template), class: 'btn btn-secondary'%>
</div>