config/routes.rb
Rails.application.routes.draw do

  # action groups
  resources :action_groups, path: 'aktionsgruppen'
  get ':id/aktionen', to: 'action_groups#show', as: 'show_action_group'


  # actions & events
  resources :actions, path: 'aktionen' do
    member do
      delete :delete_leader
      get :make_visible
      get :make_invisible
      get :crop_picture
      post :contact_volunteers
      post :contact_leaders
      get :clone
    end
  end
  resources :events do
    member do
      get :enter
      get :leave
      get :register_for_participation
      delete :delete_volunteer
    end
  end


  # news entries
  resources :news_entries, path: 'news' do
    member do
      get :crop_picture
    end
  end


  # galleries
  resources :galleries do
    member do
      get :make_all_visible
      get :make_all_invisible
    end
  end
  resources :gallery_pictures do
    member do
      get :make_visible
      get :make_invisible
    end
  end


  # users & user roles
  devise_for :users, path: '',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'edit_password'},
             controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :roles, except: [:show]
  resources :users, except: [:new, :create] do
    member do
      get :confirm_delete
      post :contact_user
    end
  end
  get :unsubscribe, to: 'users#unsubscribe'


  # surveys
  scope module: 'surveys' do
    resources :templates, as: :surveys_templates, path: 'umfragen' do
      resources :submissions, as: :surveys_submissions, path: 'antworten'
    end
  end


  # messages
  post 'kontakt', to: 'messages#send_contact_mail', as: 'send_contact_mail'
  resources :orga_messages, path: 'orga-mails' do
    member do
      get :send_message
    end
  end


  # statistics
  get 'statistiken/teilnahmen', to: 'statistics#participations'
  get 'statistiken/teilnahmen/:date', to: 'statistics#participations_on_day', as: :participations_on_day
  get 'statistiken/auslastung', to: 'statistics#occupancy'
  get 'statistiken/auslastung-:title', to: 'statistics#occupancy', as: :occupancy_in_year


  # pages
  root 'pages#home'
  get '/kontakt', to: 'pages#contact', as: :contact
  get '/eigene-aktion', to: 'pages#own_action', as: :own_action
  get '/:page', to: 'pages#page', as: :show_page


  # iCal
  get 'ical/aktionen/:action_id.ics', to: 'ical#actions', as: :action_ical
  get 'ical/aktionswochen/:action_group_id.ics', to: 'ical#action_groups', as: :action_group_ical
  get 'ical/users/:ical_token/:user_id.ics', to: 'ical#users', as: :user_ical
  get 'ical/aktionen.ics', to: 'ical#all_actions', as: :all_actions_ical


  # API
  namespace :api, constraints: { format: 'json' } do
    jsonapi_resources :action_groups
    jsonapi_resources :actions
    jsonapi_resources :events
    jsonapi_resources :news_entries
    jsonapi_resources :users
    jsonapi_resources :galleries

    jsonapi_resources :gallery_pictures do
      member do
        get :rotateRight
        get :rotateLeft
      end
    end

    scope module: 'surveys' do
      resources :templates, as: :surveys_templates, path: 'umfragen' do
        resources :submissions, as: :surveys_submissions, path: 'antworten'
      end
    end

  end

end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
  before_action :set_action, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :authorize_action, except: [:index, :new, :create, :delete_volunteer]

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  respond_to :html

  def index
    authorize Action.new
    @actions = policy_scope(Action.toplevel).order(visible: :desc, picture_source: :desc)
    return unless params[:filter]
    p = filter_params
    @actions = @actions.where(visible: (p[:visibility] != 'hidden')) unless p[:visibility].blank?
    @actions = @actions.where(date: Date.parse(p[:day])) unless p[:day].blank?
  end

  def show
    # Message for contact_volunteers or contact_leaders
    @message = Message.new
    pics = @action.gallery.gallery_pictures
    pics.build if pics.any?
  end

  def new
    @action = Action.new
    @action.events.build
    authorize_action
    @action.action_group = ActionGroup.all.order(start_date: :desc).first
  end

  def clone
    redirect_to edit_action_path(@action.clone)
  end

  def edit; end

  def create
    @action = Action.new(action_params)
    authorize_action
    @action.add_leader(current_user)
    @action.visible = false
    @action.events.each {|event| event.initiative = @action}
    @action.save
    respond_with(@action)
  end

  def update
    if @action.update(action_params)
      flash[:notice] = t('action.message.updated')
    end
    respond_with(@action)
  end

  def destroy
    @action.destroy
    respond_with(@action.action_group)
  end

  def delete_leader
    leader = User.find(params[:user_id])
    @action.delete_leader(leader)
    redirect_to @action, notice: t('action.message.leaderRemoved')
  end

  def make_visible
    @action.make_visible!
    if @action.subactions
      @action.subactions.each { |action| action.make_visible! }
    end
    redirect_to @action, notice: t('action.message.madeVisible')
  end

  def make_invisible
    @action.make_invisible!
    if @action.subactions
      @action.subactions.each { |action| action.make_invisible! }
    end
    redirect_to @action, notice: t('action.message.madeInvisible')
  end

  def crop_picture
    if params.has_key?(:crop_x)
      @action.crop_picture(params[:crop_x].to_i, params[:crop_y].to_i,
                           params[:crop_w].to_i, params[:crop_h].to_i,
                           params[:crop_target].to_sym)
      redirect_to @action, notice: t('action.message.imageCropped')
    else
      @crop_target_symbol = params[:crop_target].to_sym
      case @crop_target_symbol
      when :action_list
        @crop_target_title = t('action.heading.cropTarget.action_list')
        @crop_target_ratio = 200.0/165
      when :action_view
        @crop_target_title = t('action.heading.cropTarget.action_view')
        @crop_target_ratio = 522.0/261
      when :thumbnail
        @crop_target_title = t('action.heading.cropTarget.thumbnail')
        @crop_target_ratio = 100.0/100
      end
      respond_with @action do |format|
        format.html { render :layout => false}
      end
    end
  end

  def contact_leaders
    @message = Message.new(params[:message])
    recipients = @action.leaders + [sender]
    recipients.uniq.each do |recipient|
      Mailer.contact_leaders_mail(@message, current_user, recipient, @action).deliver_now
    end
    flash[:notice] = t('mailer.contact_leaders_mail.success')
    redirect_to action: :show
  end

  def contact_volunteers
    @message = Message.new(params[:message])
    recipients = @action.volunteers + @action.leaders + [current_user]
    if @message.recipient_scope == 'action_and_subactions'
      recipients += @action.volunteers_in_subactions + @action.leaders_in_subactions
    end
    recipients.uniq.each do |recipient|
      Mailer.contact_volunteers_mail(@message, current_user, recipient, @action).deliver_now
    end
    flash[:notice] = t('mailer.contact_volunteers_mail.success')
    redirect_to action: :show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_action
    @action = Action.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def action_params
    params.require(:the_action).permit(:title, :user_id,
                                       :location, :latitude, :longitude, :map_latitude, :map_longitude, :map_zoom,
                                       :description, :short_description, :individual_tasks, :material, :requirements,
                                       :picture, :picture_source,  :action_group_id, :parent_action_id,
                                       events_attributes: [:id, :desired_team_size, :date, :time, :_destroy])
  end

  def authorize_action
    authorize @action
  end

  def filter_params
    params.require(:filter).permit(:visibility, :date)
  end

end

app/controllers/api/actions_controller.rb
class Api::ActionsController < Api::ApiController

  include JSONAPI::ActsAsResourceController

  private

  def context
    { user: current_user }
  end

end

app/helpers/actions_helper.rb
module ActionsHelper

  # creates a comma separated list of all user names (+ anonymous user count)
  # (currently unused)
  def list_users(users)
    existing_users = users.where(cleared: false)
    deleted_users_count = users.where(cleared: true).count
    output = existing_users.map { |v| link_to(v.first_name, user_path(v)) }.join(', ')
    if deleted_users_count > 0
      output += ' + ' if existing_users.count > 0
      output += deleted_users_count.to_s + ' ' + User.model_name.human(count: deleted_users_count)
    end
    output.html_safe
  end

  # gives a list of all possible parent actions
  def possible_parent_actions(action)
    actions = action.action_group ? action.action_group.actions : Action.where(action_group: nil)
    actions = policy_scope(actions.where(parent_action_id: nil)) - [action]
    actions.pluck(:title, :id)
  end

  def show_invisible_pictures_notification?(gallery)
    return false unless current_user
    gallery.gallery_pictures.invisible.where(uploader_id: current_user.id).any? ||
        (current_user&.in_orga_team? && gallery.gallery_pictures.invisible.any?)
  end

  def has_gallery_pictures?(gallery)
    gallery && policy_scope(gallery.gallery_pictures).any?
  end

end

app/views/actions/_action_card_list.erb
<div class="action-card-list card-deck">

  <% actions.each do |action| %>

    <div class="card action-card" data-class="ClickableCard" data-href="<%= url_for action %>" title="<%= action.title %>">

      <%= image_tag action.show_picture? ? action.picture_url(:action_list) : 'placeholder.svg',
                    lazy:true, class: 'card-img-top' %>

      <div class="card-body">

        <h4 class="card-title"><%= link_to action.title, action %></h4>

        <% unless action.visible? %>
          <span class="badge status_hidden %>"><%= t('action.info.status.hidden')%></span>
        <% end %>
        <% if action.finished? %>
          <span class="badge status_finished"><%= t('action.info.status.finished') %></span>
        <% elsif action.status == :full %>
          <span class="badge status_full"><%= t('action.info.status.full') %></span>
        <% else %>
          <span class="badge status_<%= action.status %>">
            <%= "#{action.total_team_size} / #{action.total_desired_team_size}" %>
          </span>
        <% end %>

        <% if (subactions = policy_scope(action.subactions)).any? %>
          <span class="badge badge-secondary"><%= t('action.info.subactions', count: subactions.count) %></span>
        <% end %>

        <p class="card-text"><%= action.short_description.presence || action.description %></p>
      </div>
    </div>

  <% end %>

</div>

app/views/actions/_action_entry.erb
<%# expects parameters "action/event", optionally "simple_titles", "show_occupancy" and "show_date" %>
<% simple_title = local_assigns.fetch :simple_title, false %>
<% show_occupancy = local_assigns.fetch :show_occupancy, true %>
<% show_date = local_assigns.fetch :show_date, true %>
<% action = local_assigns.fetch(:action) {event.initiative} %>

<% if local_assigns.has_key? :event %>
  <% date, team_size, desired_team_size, status = event.date, event.team_size, event.desired_team_size, event.status %>
<% else %>
  <% date, team_size, desired_team_size, status = action.date, action.total_team_size, action.total_desired_team_size, action.status %>
<% end %>



<%= link_to action, class: (action.visible? ? 'action-entry' : 'action-entry hidden-action') do %>

  <div class="image">
    <%= image_tag (action.show_picture? ? action.picture_url(:action_list) : 'placeholder.svg') %>
  </div>

  <div class="info">
    <% if show_date && !date.nil? %>
      <div class="date"><%= l date, format: :date %></div>
    <% end %>
    <% if !simple_title && action.subaction? %>
      <div class="parent-title"><%= action.parent_action.title %></div>
    <% end %>
    <div class="title"><%= action.title %></div>
  </div>

  <% if show_occupancy && desired_team_size.positive? %>
    <div class="badges">
      <% if [:empty, :soon_full, :full].include? status %>
          <span class="badge status_<%= status %>"
                title="<%= t('action.info.remainingVacancy', places: desired_team_size - team_size) %>">
                <%= "#{team_size} / #{desired_team_size}" %>
              </span>
      <% end %>
    </div>
  <% end %>

<% end %>

app/views/actions/_form.erb
<% wrapper_set 'container-medium' %>

<% content_for :end_of_body do %>
  <div id="image_crop_modal" class="modal fade" tabindex="-1" role="dialog" data-class="Modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
      </div>
    </div>
  </div>
<% end %>

<%= bootstrap_form_for(@action, as: :the_action) do |f| %>

  <% if @action.errors.any? %>
    <section id="error_explanation">
      <h2><%= t('action.message.errorList') %></h2>
      <ul>
        <% @action.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </section>
  <% end %>

  <div class="white-box record-header">
    <% if isNew %>
      <h1><%= t('action.heading.new') %></h1>
    <% else %>
      <div class="type"><%= t('action.heading.edit') %></div>
      <h1><%= @action.title %></h1>
    <% end %>
  </div>

  <div class="row align-items-stretch">
    <div class="col-sm-8">

      <div class="white-box">
        <%= f.text_field :title %>
        <div class="form-group">
          <label class="control-label" for="action_picture_source">
            <%= Action.human_attribute_name(:picture) %>
          </label>
          <%= f.file_field :picture, hide_label: true %>

          <% if @action.picture.file %>
            <div class="action-picture picture-container">
              <%= image_tag @action.picture_url(:action_view) %>
            </div>
            <% if @action.persisted? %>
              <%= link_to crop_picture_action_path(@action, crop_target: 'action_list'),
                          class: 'btn btn-secondary', data: {toggle: 'modal', target: '#image_crop_modal'} do %>
                <span class="fas fa-crop"></span> <%= t('action.button.cropListviewImage') %>
              <% end %>
              <%= link_to crop_picture_action_path(@action, crop_target: 'action_view'),
                          class: 'btn btn-secondary', data: {toggle: 'modal', target: '#image_crop_modal'}  do %>
                <span class="fas fa-crop"></span> <%= t('action.button.cropActionImage') %>
              <% end %>
              <%= link_to crop_picture_action_path(@action, crop_target: 'thumbnail'),
                          class: 'btn btn-secondary', data: {toggle: 'modal', target: '#image_crop_modal'} do %>
                <span class="fas fa-crop"></span> <%= t('action.button.cropThumbnailImage') %>
              <% end %>

            <% end %>
          <% end %>

        </div>
        <%= f.text_field :picture_source, help: t('action.help.picture_source') %>
      </div>

      <div class="white-box">
        <div class="short_description">
          <%= f.text_area :short_description, help: t('action.help.short_description') %>
        </div>
        <div class="description">
          <%= f.text_area :description %>
        </div>
        <div class="individual_tasks">
          <%= f.text_area :individual_tasks %>
        </div>
        <div class="requirements">
          <%= f.text_area :requirements %>
        </div>
        <div class="material">
          <%= f.text_area :material %>
        </div>
      </div>

    </div>
    <div class="col-sm-4">

      <div class="white-box">
        <h3>
          <%= t('action.heading.management') %>
        </h3>
        <%= button_tag class: 'btn btn-success btn-block' do %>
          <span class="fas fa-save"></span> <%= t('general.button.save') %>
        <% end %>
        <% if isNew %>
          <%= link_to :back, class: 'btn btn-warning btn-block' do %>
            <span class="fas fa-ban"></span> <%= t('general.button.cancel') %>
          <% end %>
        <% else %>
          <%= link_to @action, class: 'btn btn-warning btn-block' do %>
            <span class="fas fa-ban"></span> <%= t('general.button.cancel') %>
          <% end %>
          <%= link_to clone_action_path(@action), class: 'btn btn-dark btn-block' do %>
            <span class="far fa-copy"></span> <%= t('action.button.clone') %>
          <% end %>
        <% end %>
        <% if !isNew && policy(@action).destroy? %>
          <%= link_to @action, method: :delete, class: 'btn btn-danger btn-block',
                      data: { confirm: t('general.message.confirmDelete')} do %>
            <span class="fas fa-trash"></span> <%= t('general.button.delete') %>
          <% end %>
        <% end %>
      </div>

      <div class="white-box">
        <div class="week">
          <%= f.collection_select(:action_group_id, ActionGroup.all.order(title: :desc), :id, :title,
                                  {selected: @action.action_group&.id, include_blank: true}) %>
        </div>
        <div class="parent_action">
          <%= f.select(:parent_action_id, possible_parent_actions(@action), {include_blank: true}) %>
        </div>
        <div class="location">
          <%= f.text_area :location %>
        </div>
        <div>
          <div class="map" data-class="GoogleMap" data-map-id="the_action"
               data-lon="<%= @action.map_longitude %>"
               data-lat="<%= @action.map_latitude %>"
               data-zoom="<%= @action.map_zoom %>">
            <div class="markers">
              <div data-lon="<%= @action.longitude %>"
                   data-lat="<%= @action.latitude %>"
                   data-name="<%= @action.title %>"
                   data-editable="true">test
              </div>
            </div>
          </div>
          <%= f.text_field :longitude, type: :hidden, hide_label: true %>
          <%= f.text_field :latitude, type: :hidden, hide_label: true %>
          <%= f.text_field :map_longitude, type: :hidden, hide_label: true %>
          <%= f.text_field :map_latitude, type: :hidden, hide_label: true %>
          <%= f.text_field :map_zoom, type: :hidden, hide_label: true %>
        </div>
      </div>

      <div class="white-box events" data-class="DynamicFormList">
        <div class="prototype d-none">
          <% new_object = f.object.class.reflect_on_association(:events).klass.new %>
          <%= f.fields_for(:events, new_object, child_index: :new_item) {
              |builder| render('events/event_fields', f: builder, default_date: @action.action_group&.start_date)} %>
        </div>
        <%= f.fields_for :events do |builder| %>
          <%= render 'events/event_fields', f: builder, default_date: @action.action_group&.start_date %>
        <% end %>
        <%= link_to t('action.button.addEvent'), 'javascript:void(0);', class: 'add-link btn btn-secondary' %>
      </div>

    </div>

  </div>

<% end %>

app/views/actions/edit.erb
<% provide :title, t('layout.title.action.edit', action:@action.title) %>

<%= render 'form', isNew: false %>

app/views/actions/index.erb
<% provide :title, t('layout.title.action.list') %>
<% wrapper_set %>



<div class="white-box">
  <h1>Aktionen</h1>
</div>

<div class="white-box container-small">
  <h3>Optionen</h3>
  <%= link_to 'Neue Aktion', new_action_path, class:'btn btn-primary btn-block' %>
</div>

<%= render 'action_card_list', actions: @actions %>

app/views/actions/new.erb
<% provide :title, t('layout.title.action.new') %>

<%= render 'form', isNew: true %>

app/views/actions/show.erb
<% provide :title, 'Aktion "' + @action.title + (@action.parent_action ? (' - ' + @action.parent_action.title) : '') + '"'%>
<% wrapper_set 'container-medium' %>
<% wrapper_classes.add('action-invisible') unless @action.visible? %>

<% content_for :head do %>
  <meta name="description" content="<%= strip_tags @action.short_description %>" />
  <% if @action.show_picture? %>
    <meta property="og:image" content="<%= image_url(@action.picture_url) %>" />
  <% end %>
  <meta property="og:description" content="<%= strip_tags @action.short_description %>" />
<% end %>

<div class="white-box record-header d-print-none">
  <div class="type">
    <%= Action.model_name.human %>
    <% if @action.action_group %>
      <%= action_group_declination(@action.action_group, :temporal) %>
      <%= link_to @action.action_group.title, show_action_group_path(@action.action_group) %>
    <% end %>
  </div>

  <h1><%= @action.full_title %></h1>
  <div class="labels">
    <% unless @action.visible? %>
      <span class="badge status_hidden"><%= t('action.info.status.hidden') %></span>
    <% end %>
    <span class="badge status_<%= @action.status %>">
        <%= t "action.info.status.#{@action.status}" %>
      </span>
  </div>
</div>

<div class="row align-items-stretch">
  <div class="col-md-8">
    <div class="row parent-height align-items-stretch">
      <div class="col-12">

        <section class="white-box">
          <h2 class="d-print-only"><%= @action.title %></h2>

          <%# action picture %>
          <% if @action.show_picture? && @action.picture.file %>
            <div class="action-picture picture-container">
              <%= image_tag @action.picture_url(:action_view) %>
              <div class="copyright" title="© <%= @action.picture_source %>">
                © <%= @action.picture_source %>
              </div>
            </div>
          <% end %>

          <%# action description %>
          <div class="description">
            <%= simple_format( simple_format_urls @action.description ) %>
          </div>
          <% unless @action.individual_tasks.blank? %>
            <div class="individual_tasks">
              <h3><%= Action.human_attribute_name(:individual_tasks) %></h3>
              <%= simple_format( simple_format_urls @action.individual_tasks) %>
            </div>
          <% end %>
          <% unless @action.requirements.blank? %>
            <div class="requirements">
              <h3><%= Action.human_attribute_name(:requirements) %></h3>
              <%= simple_format( simple_format_urls @action.requirements) %>
            </div>
          <% end %>
          <% unless @action.material.blank? %>
            <div class="material">
              <h3><%= Action.human_attribute_name(:material) %></h3>
              <%= simple_format( simple_format_urls @action.material) %>
            </div>
          <% end %>

        </section>

      </div>

      <%# gallery %>
      <% if has_gallery_pictures?(@action.gallery) || policy(@action).upload_pictures? %>
        <div class="col-12">
          <section id="actions-gallery" class="white-box d-print-none">
            <%= render 'galleries/action_gallery', gallery: @action.gallery %>
          </section>
        </div>
      <% end %>

      <%# communication %>
      <% if policy(@action).contact_volunteers? %>
        <div class="col-12">
          <section id="action-communication" class="white-box d-print-none">
            <%= bootstrap_form_for(@message, url: {action: 'contact_volunteers'}) do |f| %>
              <h3><%= t('action.heading.contactTeam') %></h3>
              <p><%= t('action.help.contactTeam') %></p>
              <% if user_signed_in? && current_user.admin? %>
                <p>(<%= (@action.volunteers + @action.leaders + [current_user]).uniq.map { |v| v.email}.join(', ') %>)</p>
              <% end %>
              <%= f.select :recipient_scope, [
                  [t('action.form.contactTeam.recipient_scopes.this_action'), 'this_action'],
                  [t('action.form.contactTeam.recipient_scopes.action_and_subactions'), 'action_and_subactions']],
                           {label: t('action.form.contactTeam.recipient_scope')}, class: 'selectpicker' %>
              <%= f.text_field :subject, label: t('action.form.contactTeam.subject') %>
              <%= f.text_area :body, label: t('action.form.contactTeam.message') %>
              <%= f.submit t('action.button.contactTeam'), class: 'btn btn-primary' %>
            <% end %>
          </section>
        </div>
      <% elsif policy(@action).contact_leaders? %>
        <div class="col-12">
          <section id="action-communication" class="white-box d-print-none">
            <%= bootstrap_form_for(@message, url: {action: 'contact_leaders'}) do |f| %>
              <h3><%= t('action.heading.contactLeader') %></h3>
              <p><%= t('action.help.contactLeader') %></p>
              <%= f.text_field :subject, label: t('action.form.contactLeader.subject') %>
              <%= f.text_area :body, label: t('action.form.contactLeader.body') %>
              <%= f.submit t('action.button.contactLeader'), class: 'btn btn-primary' %>
            <% end %>
          </section>
        </div>
      <% end %>

    </div>
  </div>

  <div class="col-md-4">
    <div class="row align-items-stretch">

      <%# control panel %>
      <% if policy(@action).edit? %>
        <div class="col-sm-6 col-md-12 d-print-none">
          <section class="white-box">
            <%= link_to edit_action_path(@action), class:'btn btn-primary btn-block' do %>
              <span class="fas fa-pencil-alt"></span> <%= t('action.button.edit') %>
            <% end %>
            <% if policy(@action).change_visibility? %>
              <% if @action.visible %>
                <%= link_to make_invisible_action_path(@action), class:'btn status_hidden btn-block' do %>
                  <span class="fas fa-eye-slash"></span> <%= t('action.button.makeInvisible') %>
                <% end %>
              <% else %>
                <%= link_to make_visible_action_path(@action), class:'btn status_hidden btn-block' do %>
                  <span class="fas fa-eye"></span> <%= t('action.button.makeVisible') %>
                <% end %>
              <% end %>
            <% end %>
          </section>
        </div>
      <% end %>

      <%# action date/location info %>
      <div class="col-sm-6 col-md-12">
        <% unless @action.parent_action.nil? %>
          <div class="white-box">
            <h3>Die Aktion ist ein Teil von</h3>
            <%= render '/actions/action_entry', action: @action.parent_action, show_date: false, show_occupancy: false %>
          </div>
        <% end %>
        <div class="white-box">
          <div id="action-leaders" class="mb-2">
            <h3><%= Action.human_attribute_name('leaders') %></h3>
            <div class="comma-list">
              <% @action.leaders.each do |leader| %>
                <span>
                  <%= link_to leader.first_name, leader %>
                  <% if policy(@action).manage_team? %>
                    <%= api_link '', [@action, 'leaders', leader], :remove, data: {'success-remove': 1} %>
                  <% end %>
                </span>
              <% end %>
            </div>
            <% if policy(@action).manage_team? && policy(User).index? %>
              <div class="my-2">
                <%= user_select_picker @action, 'leaders', false, class: 'col-select btn-block',
                                       title: t('action.button.addLeader'), data: {'success-reload': true} %>
              </div>
            <% end %>
          </div>
          <div>
            <h3><%= Action.human_attribute_name('date'.pluralize(@action.dates.count)) %></h3>
            <% if @action.subactions.empty? %>
              <% @action.events.each do |event| %>
                <div>
                  <%= l(event.date, format: :short_with_weekday) unless event.date.nil? %><%= (', ' + event.time) unless event.time.nil? %>
                </div>
              <% end %>
            <% else %>
              <%= @action.dates.uniq.sort.collect { |date| l(date, format: :short_with_weekday)}.join('<br />').html_safe %>
            <% end %>
          </div>
          <div>
            <h3><%= Action.human_attribute_name(:location) %></h3>
            <%= simple_format @action.location %>
          </div>
          <% unless @action.longitude == 0 %>
            <div class="map d-print-none" data-class="GoogleMap" data-map-id="action"
                 data-zoom="<%= @action.map_zoom %>"
                 data-lon="<%= @action.map_longitude %>"
                 data-lat="<%= @action.map_latitude %>">
              <div class="markers">
                <div data-name="<%= @action.title %>"
                     data-lon="<%= @action.longitude %>"
                     data-lat="<%= @action.latitude %>">
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <%# sub actions %>
      <% subactions = policy_scope(@action.subactions).sort_by { |p| p.start_time || p.date || Time.now } %>
      <% if subactions.any? %>
        <div class="col-sm6 col-md-12">
          <div class="white-box">
            <div id="subaction-list">
              <h3><%= Action.human_attribute_name(:subaction_ids) %></h3>
              <% subactions.each do |action| %>
                <%= render '/actions/action_entry', action: action, simple_title: true %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>

      <%# team info %>
      <div class="col-sm-6 col-md-12 d-print-none">
        <% if @action.desired_team_size.positive? %>
          <%= render 'events/event_team_list', events: @action.events %>
        <% elsif user_signed_in? && @action.volunteers_in_subactions.include?(current_user) %>
          <div class="white-box">
            <p class="h4 my-0"><%= t('action.info.subactionTeamMember') %></p>
          </div>
        <% elsif @action.available_places.zero? && @action.total_available_places.positive? %>
          <div class="white-box">
            <p class="h4 my-0"><%= t('action.info.enterOneOfThesubactions') %></p>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

<div class="footer d-print-none">
  <%= render '/layouts/share' %>
  <%= link_to action_ical_path(@action), class: 'float-right px-1',
              title: t('action.button.exportICal'), data: { 'turbolinks': false } do %>
    <span class="far fa-calendar-alt fa-2x"></span>
  <% end %>
  <% if @action.action_group %>
    <%= link_to t('action.navigation.toOverview'), show_action_group_path(@action.action_group), class: 'btn btn-light' %>
  <% end %>
  <% if @action.parent_action %>
    <%= link_to t('action.navigation.toParentAction'), @action.parent_action, class: 'btn btn-light' %>
  <% end %>
</div>