config/routes.rb
Rails.application.routes.draw do

  # action groups
  resources :action_groups, path: 'aktionsgruppen'
  get ':id/aktionen', to: 'action_groups#show', as: 'show_action_group'


  # actions & events
  resources :actions, path: 'aktionen' do
    member do
      delete :delete_leader
      get :make_visible
      get :make_invisible
      get :crop_picture
      post :contact_volunteers
      post :contact_leaders
      get :clone
    end
  end
  resources :events do
    member do
      get :enter
      get :leave
      get :register_for_participation
      delete :delete_volunteer
    end
  end


  # news entries
  resources :news_entries, path: 'news' do
    member do
      get :crop_picture
    end
  end


  # galleries
  resources :galleries do
    member do
      get :make_all_visible
      get :make_all_invisible
    end
  end
  resources :gallery_pictures do
    member do
      get :make_visible
      get :make_invisible
    end
  end


  # users & user roles
  devise_for :users, path: '',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'edit_password'},
             controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :roles, except: [:show]
  resources :users, except: [:new, :create] do
    member do
      get :confirm_delete
      post :contact_user
    end
  end
  get :unsubscribe, to: 'users#unsubscribe'


  # surveys
  scope module: 'surveys' do
    resources :templates, as: :surveys_templates, path: 'umfragen' do
      resources :submissions, as: :surveys_submissions, path: 'antworten'
    end
  end


  # messages
  post 'kontakt', to: 'messages#send_contact_mail', as: 'send_contact_mail'
  resources :orga_messages, path: 'orga-mails' do
    member do
      get :send_message
    end
  end


  # statistics
  get 'statistiken/teilnahmen', to: 'statistics#participations'
  get 'statistiken/teilnahmen/:date', to: 'statistics#participations_on_day', as: :participations_on_day
  get 'statistiken/auslastung', to: 'statistics#occupancy'
  get 'statistiken/auslastung-:title', to: 'statistics#occupancy', as: :occupancy_in_year


  # pages
  root 'pages#home'
  get '/kontakt', to: 'pages#contact', as: :contact
  get '/eigene-aktion', to: 'pages#own_action', as: :own_action
  get '/:page', to: 'pages#page', as: :show_page


  # iCal
  get 'ical/aktionen/:action_id.ics', to: 'ical#actions', as: :action_ical
  get 'ical/aktionswochen/:action_group_id.ics', to: 'ical#action_groups', as: :action_group_ical
  get 'ical/users/:ical_token/:user_id.ics', to: 'ical#users', as: :user_ical
  get 'ical/aktionen.ics', to: 'ical#all_actions', as: :all_actions_ical


  # API
  namespace :api, constraints: { format: 'json' } do
    jsonapi_resources :action_groups
    jsonapi_resources :actions
    jsonapi_resources :events
    jsonapi_resources :news_entries
    jsonapi_resources :users
    jsonapi_resources :galleries

    jsonapi_resources :gallery_pictures do
      member do
        get :rotateRight
        get :rotateLeft
      end
    end

    scope module: 'surveys' do
      resources :templates, as: :surveys_templates, path: 'umfragen' do
        resources :submissions, as: :surveys_submissions, path: 'antworten'
      end
    end

  end

end

app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :participations, dependent: :destroy
  has_many :events_as_volunteer, through: :participations, source: :event
  has_many :leaderships, dependent: :destroy
  has_many :actions_as_leader, through: :leaderships, source: :action
  has_and_belongs_to_many :roles

  USERNAME_FORMAT = /\A[\w]+\z/

  validates_presence_of :username, :first_name, :last_name, :email
  validates :username,
            uniqueness: { case_sensitive: false },
            format: { with: USERNAME_FORMAT, message: I18n.t('activerecord.errors.messages.onlyLetters') },
            length: { in: 2..50 }
  validates :email,
            uniqueness: { case_sensitive: false },
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i },
            length: { in: 5..100 }
  validates :first_name,
            length: { in: 2..50 },
            format: { with: /\A[[[:word:]]-\.]+( [[[:word:]]-\.]+)*\z/, message: I18n.t('activerecord.errors.messages.onlyWordsAndInnerSpace') }
  validates :last_name,
            length: { in: 2..50 },
            format: { with: /\A[[[:word:]]-\.]+( [[[:word:]]-\.]+)*\z/, message: I18n.t('activerecord.errors.messages.onlyWordsAndInnerSpace') }
  attr_accessor :login
  has_secure_token :ical_token

  before_validation :set_default_username_if_blank!, on: :create

  scope :valid,  -> { where(users: { cleared: false }) }



  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    if login
      where(conditions.to_hash).where(['lower(username) = :value OR lower(email) = :value', { :value => login.downcase }]).first
    else
      conditions[:email].downcase! if conditions[:email]
      where(conditions.to_hash).first
    end
  end

  def full_name
    first_name + ' ' + last_name
  end

  def leads_action?(action)
    actions_as_leader.include? action
  end

  def actions
    Action.joins(:leaderships).joins('JOIN events eventsUser ON eventsUser.initiative_id = actions.id')
        .joins('JOIN participations ON participations.event_id = eventsUser.id')
        .where('participations.user_id = ? OR leaderships.user_id = ?', id, id).distinct
  end

  def actions_as_volunteer
    Action.joins('JOIN events ON events.initiative_id = actions.id')
        .joins('JOIN participations ON participations.event_id = events.id')
        .where('participations.user_id = ?', id).distinct
  end

  def events # TODO sure this works as intended?
    Event.joins(:participations).where('participations.user_id': id)
        .joins('JOIN actions ON events.initiative_id = actions.id')
        .joins('JOIN leaderships ON leaderships.action_id = actions.id')
        .where('leaderships.user_id': id).distinct
  end

  def events_as_volunteer
    Event.joins(:participations).where('participations.user_id': id).distinct
  end

  # based on https://github.com/refinery/refinerycms/blob/master/authentication/app/models/refinery/user.rb
  def add_role(title)
    raise ArgumentError, 'Role should be the title of the role not a role object.' if title.is_a?(Role)
    roles << Role.find {|r| r.title.camelize == title.to_s.camelize} unless has_role?(title)
  end

  # based on https://github.com/refinery/refinerycms/blob/master/authentication/app/models/refinery/user.rb
  def has_role?(title)
    raise ArgumentError, 'Role should be the title of the role not a role object.' if title.is_a?(Role)
    roles.any?{|r| r.title.camelize == title.to_s.camelize}
  end

  def admin?
    has_role?(:admin)
  end

  def coordinator?
    has_role?(:coordinator)
  end

  def in_orga_team?
    admin? || coordinator?
  end

  def photographer?
    has_role?(:photographer)
  end

  def clear!
    self.first_name = 'cleared'
    self.last_name = 'cleared'
    self.phone = ''
    self.username = ''
    set_default_username_if_blank!
    self.email = self.username + '@cleared.servethecity-karlsruhe.de'
    self.cleared = true
  end

  def merge_other_users_actions(other_user)
    other_user.events_as_volunteer.to_a.each do |event|
      unless event.volunteer?(self)
        event.delete_volunteer(other_user)
        event.add_volunteer(self)
      end
    end

    other_user.actions_as_leader.to_a.each do |action|
      unless action.leader?(self)
        action.delete_leader(other_user)
        action.add_leader(self)
      end
    end
  end

  private

  def set_default_username_if_blank!  # not thread safe
    return unless username.blank?
    possible_usernames = [first_name, "#{first_name}#{last_name.first}", "#{first_name}#{last_name}"]
    possible_usernames.each do |new_name|
      unless username_exists_in_database? new_name
        self.username = new_name
        break
      end
    end
    max_num = 10 * User.count
    tries = 0
    while username.blank?
      new_name = "user#{rand(max_num)}"
      self.username = new_name unless username_exists_in_database? new_name
      tries += 1
      if tries > 1000
        logger.error "No username could be generated within #{tries} tries. Returning #{new_name}. First name: #{first_name}, last name: #{last_name}, max_num: #{max_num}"
        return new_name
      end
    end
  end

  def username_exists_in_database?(username)
    User.where('lower(username) = ?', username.downcase).count > 0 || !USERNAME_FORMAT.match(username)
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::ApiController

  include JSONAPI::ActsAsResourceController

  private

  def context
    { user: current_user }
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  respond_to :json

  def create
    if verify_recaptcha
      super
    else
      build_resource(sign_up_params)
      clean_up_passwords(resource)
      flash.now[:error] = flash[:recaptcha_error]
      flash.delete :recaptcha_error
      render :new
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  respond_to :json

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:index, :unsubscribe]
  before_action :authorize_user, except: [:index, :unsubscribe]
  after_action :verify_authorized

  respond_to :html

  def index
    authorize User.new
    @users = User.all.order(:created_at)
    respond_with(@users)
  end

  def show
    if @user.id === current_user.id
      template = Surveys::Template.where(show_in_user_profile: true).order('RANDOM()').first
      if template && !template.submissions.where(user_id: current_user.id).exists?
        @submission = Surveys::Submission.create_for_template(template)
      end
    else
      # Message for contact_user
      @message = Message.new
    end
    respond_with(@user)
  end

  def edit
    respond_with(@user)
  end

  def update
    @user.update(user_params)
    respond_with(@user)
  end

  def confirm_delete
    respond_with(@user)
  end

  def unsubscribe
    @user = SignedGlobalID.find(params[:sgid], for: :unsubscribe_user)
    @type = params[:type].to_sym
    authorize_user
    allowed_types = [:receive_emails_about_action_groups,
                     :receive_emails_about_my_action_groups,
                     :receive_emails_about_other_projects,
                     :receive_other_emails_from_orga]
    if @type == :all_emails
      allowed_types.each do |t|
        @user.update_attribute t, false
      end
    elsif allowed_types.include? @type
      @user.update_attribute @type, false
    end
    respond_with(@user)
  end

  def destroy
    if @user.valid_password?(params[:confirm_delete_password]) || current_user.admin?
      @user.clear!
      @user.save!
      sign_out
      redirect_to root_path, notice: t('user.message.accountDeleted')
    else
      redirect_to action: :confirm_delete, alert: t('user.message.invalidPassword')
    end
  end

  def contact_user
    @message = Message.new(params[:message])
    Mailer.user_mail(@message, current_user, @user).deliver_now
    flash[:notice] = t('mailer.user_mail.success', recipient: @user.full_name)
    redirect_to action: :show
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :email, :phone,
                                 :receive_emails_about_action_groups, :receive_emails_about_my_action_groups, :receive_emails_about_other_projects,
                                 :receive_other_emails_from_orga, :receive_emails_from_other_users)
  end

  def authorize_user
    authorize @user
  end

end

app/helpers/users_helper.rb
module UsersHelper

  # Infers the value of the "Receive orga mails" checkbox in the user profile edit page
  def receive_email_from_orga user
    user.receive_emails_about_action_groups || user.receive_emails_about_my_action_groups ||
        user.receive_emails_about_other_projects || user.receive_other_emails_from_orga
  end

  # Summarizes orga mail settings for the user profile page
  def email_reception_description user
    if receive_email_from_orga(user) && user.receive_emails_from_other_users
      t('user.info.emailReception.orgaAndUser')
    elsif receive_email_from_orga user
      t('user.info.emailReception.orga')
    elsif user.receive_emails_from_other_users
      t('user.info.emailReception.user')
    else
      t('user.info.emailReception.none')
    end
  end
  
end

app/views/users/_login_form.erb
<% unless defined? in_other_form %>
  <h2><%= t('user.heading.login') %></h2>
<% end %>

<%= bootstrap_form_for(resource, as: resource_name, namespace: 'page_login', url: session_path(resource_name)) do |f| %>

  <div class="row">
    <div class="col-sm-6">
      <%= f.text_field :login, autofocus: true, label: t('user.form.usernameOrEmail') %>
    </div>
    <div class="col-sm-6">
      <%= f.password_field :password %>
    </div>
  </div>


  <% if devise_mapping.rememberable? %>
    <%= f.check_box :remember_me %>
  <% end %>

  <%= button_tag class: 'btn btn-primary' do %>
    <span class="fas fa-sign-in-alt"></span> <%= t('user.button.login') %>
  <% end %>

  <% if devise_mapping.recoverable? %>
    <%= link_to new_password_path(resource_name), class:'btn btn-link' do %>
      <%= t('user.button.recoverPassword') %>
    <% end %>
  <% end %>

  <% unless defined? in_other_form %>
    <%= link_to new_registration_path(resource_name), class:'btn btn-link' do %>
      <%= t('user.button.showRegistration') %>
    <% end %>
  <% end %>

  <% if devise_mapping.omniauthable? %>
    <% resource_class.omniauth_providers.each do |provider| %>
      <%= link_to omniauth_authorize_path(resource_name, provider), class:'btn btn-secondary' do %>
        <span class="fab fa-openid"></span> <%= t('user.button.loginWithProvider', provider: provider.to_s.titleize) %>
      <% end %>
    <% end %>
  <% end %>

<% end %>

app/views/users/_register_form.erb
<% unless defined? in_other_form %>
  <h2><%= t('user.heading.register') %></h2>
<% end %>

<%= bootstrap_form_for(resource, as: resource_name, namespace: 'page_reg', url: registration_path(resource_name)) do |f| %>

  <%#= devise_error_messages! %>

  <div class="row">
    <div class="col-sm-6">
      <%= f.text_field :first_name, autofocus: true %>
    </div>
    <div class="col-sm-6">
      <%= f.text_field :last_name %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <%= f.email_field :email %>
    </div>
    <div class="col-sm-6">
      <%= f.text_field :phone, label: t('user.form.phoneOptional') %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <%= f.password_field :password, help: t('user.help.passwordLength'), label: t('user.form.passwordSet') %>
    </div>
    <div class="col-sm-6">
      <%= f.form_group do %>
        <%= recaptcha_tags ajax: true, script: false %>
      <% end %>
    </div>
  </div>

  <p>
    <b>Verwendung der Daten</b><br />
    Wir erheben die Daten zum Zweck der Profilerstellung und der Anmeldung zu Aktionen.
    Auf Aktionen wird dein Vorname angezeigt, wenn du dich dafür angemeldet hast.
    Andere angemeldete User können auf dein Profil zugreifen und dort deinen ganzen Namen sowie deine Aktionen sehen.
    Deine E-Mail-Adresse ist generell unsichtbar und wird nur zur (anpassbaren) Kontaktaufnahme per
    Formular durch Aktionsleiter, andere User oder Serve the City verwendet.
    Wenn du deine Handynummer angibst, kann dich der Leiter besser erreichen,
    falls du dich z.B. verspätest oder es organisatorische Änderungen gibt.
    Weitere Infos findest du auf unserer <a href="/datenschutz" target="_blank">Datenschutz-Seite</a>.
  </p>

  <%= button_tag class: 'btn btn-primary' do %>
    <span class="fas fa-user-plus"></span> <%= t('user.button.register') %>
  <% end %>
<% end %>

app/views/users/confirm_delete.erb
<% provide :title, t('layout.title.userDeleteAccount', user:@user.full_name) %>
<% wrapper_set 'white-box', 'container-small' %>

<h1><%= t('user.heading.deleteAccount') %></h1>

<%= bootstrap_form_tag url: user_path(@user), method: :delete do |f| %>

  <%= f.password_field :confirm_delete_password, label: t('user.form.confirmDeletePassword') %>

  <%= button_tag class: 'btn btn-danger' do %>
    <span class="fas fa-trash"></span> <%= t('user.button.deleteAccount') %>
  <% end %>

<% end %>

app/views/users/edit.erb
<% provide :title, t('layout.title.userProfileEdit', user:@user.full_name) %>
<% wrapper_set 'container-medium' %>
<%= devise_error_messages! %>

<%= bootstrap_form_for(@user) do |f| %>

  <div class="white-box record-header">
    <div class="type"><%= t('user.heading.edit') %></div>
    <h1 class="align-center"><%= @user.full_name %></h1>
  </div>

  <div class="row align-items-stretch">
    <div class="col-sm-5">
      <div class="white-box">

        <h2><%= t('user.heading.userData') %></h2>
        <%= f.text_field :username %>
        <%= f.text_field :first_name %>
        <%= f.text_field :last_name %>
        <%= f.email_field :email %>
        <%= f.text_field :phone %>
        <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
            <div><%= t('user.info.waitingForEmailConfirmation',
                       email: resource.unconfirmed_email) %></div>
        <% end %>

      </div>
    </div>

    <div class="col-sm-7">
      <div class="white-box">

        <h2><%= t('user.heading.emailSettings') %></h2>
        <div class="checkbox">
          <%= label_tag :emails_from_orga do %>
              <%= check_box_tag :emails_from_orga, :emails_from_orga, receive_email_from_orga(@user) %>
              <%= t('user.form.receiveEmailsFromOrga') %>
          <% end %>
        </div>
        <div id="emails-from-orga-subitems" class="ml-4">
          <%= f.check_box :receive_emails_about_action_groups %>
          <%= f.check_box :receive_emails_about_my_action_groups %>
          <%= f.check_box :receive_emails_about_other_projects %>
          <%= f.check_box :receive_other_emails_from_orga %>
        </div>
        <%= f.check_box :receive_emails_from_other_users %>
        <%= f.check_box :receive_notifications_for_new_participation %>
        <% if @user.actions_as_leader.count > 0 %>
            <%= f.check_box :receive_notifications_about_volunteers %>
        <% end %>

      </div>
    </div>
  </div>

  <div class="white-box">
    <div class="row">
      <div class="col">
        <%= link_to edit_user_registration_path, class:'btn btn-link btn-block' do %>
          <span class="fas fa-key"></span> <%= t('user.button.changePassword') %>
        <% end %>
      </div>
      <div class="col">
        <%= link_to confirm_delete_user_path, class:'btn btn-link btn-block' do %>
          <span class="fas fa-trash"></span> <%= t('user.button.deleteAccount') %>
        <% end %>
      </div>
      <div class="col">
        <%= link_to user_path(@user), class:'btn btn-link btn-block' do %>
          <span class="fas fa-ban"></span> <%= t('general.button.cancel') %>
        <% end %>
      </div>
      <div class="col">
        <%= button_tag class:'btn btn-success btn-block' do %>
          <span class="fas fa-save"></span> <%= t('general.button.save') %>
        <% end %>
      </div>
    </div>
  </div>

<% end %>

app/views/users/index.erb
<% provide :title, t('layout.title.userList') %>

<h1><%= t('user.heading.userList') %></h1>

<table class="table">
  <thead>
    <tr>
      <th><%= User.human_attribute_name(:username) %></th>
      <th><%= User.human_attribute_name(:first_name) +' & '+ User.human_attribute_name(:last_name) %></th>
      <th><%= User.human_attribute_name(:email) %> & <%= User.human_attribute_name(:phone) %></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username , user %></td>
        <td><%= user.first_name + ' ' + user.last_name %></td>
        <td><%= user.email %> <br /> <%= user.phone %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New User', new_user_path %>

app/views/users/show.erb
<% provide :title, @user.full_name %>
<% wrapper_set 'container-medium' %>
<% own_profile = (@user == current_user) %>

<div class="white-box record-header">
  <div class="type"><%=  t('user.heading.' + (own_profile ? 'myProfile' : 'profile')) %></div>
  <h1 class="align-center"><%= @user.full_name %></h1>
</div>

<div class="row align-items-stretch">
  <div class="col-sm-5">

    <% if own_profile && @submission %>
        <section id="survey" class="white-box">
          <h2>Umfrage</h2>
          <%= bootstrap_form_for([@submission.template, @submission]) do |f| %>
              <%= render '/surveys/submissions/form_questions', f: f %>
              <%= f.submit t('surveys.button.saveSubmission'), class:'submit btn btn-secondary float-right' %>
          <% end %>
        </section>
    <% end %>

    <% if own_profile || current_user.in_orga_team? %>
        <section id="user-profile-data" class="white-box">
          <h2><%= t('user.heading.userData') %></h2>
          <table class="table table-responsive properties">
            <tr>
              <td><%= User.human_attribute_name :username %></td>
              <td><%= @user.username %></td>
            </tr>
            <tr>
              <td><%= User.human_attribute_name :email %></td>
              <td><%= @user.email %></td>
            </tr>
            <tr>
              <td><%= User.human_attribute_name :phone %></td>
              <td><%= @user.phone %></td>
            </tr>
          </table>
          <span><%= email_reception_description @user %></span>

          <div class="row mt-5">
            <div class="col">
              <% if policy(@user).edit?  %>
                <%= link_to edit_user_path, title: t('user.button.edit'), class:'btn btn-primary btn-block' do %>
                  <span class="fas fa-pencil-alt"></span>
                  <%= t('user.button.edit') %>
                <% end %>
              <% end %>
            </div>
            <div class="col">
              <%= link_to destroy_user_session_path, method: :delete, title: t('user.button.logout'), class:'btn btn-secondary btn-block' do %>
                <span class="fas fa-sign-out-alt"></span>
                <%= t('user.button.logout') %>
              <% end %>
            </div>
          </div>

        </section>
    <% end %>

    <% unless own_profile  %>
        <section id="contact-user-form" class="white-box">
          <h2><%= t('user.heading.user_mail', recipient: @user.first_name) %></h2>
          <%= bootstrap_form_for @message, url: { action: 'contact_user' } do |f| %>
              <%= f.text_field :subject, label: t('general.form.subject') %>
              <%= f.text_area :body, label: t('general.form.body') %>
              <%= f.submit t('user.button.user_mail'), class: 'btn btn-primary' %>
          <% end %>
        </section>
    <% end %>

  </div>
  <div class="col-sm-7">

    <section class="white-box">
      <h2><%= Participation.model_name.human(count: 2) %></h2>
      <% past_events = @user.events_as_volunteer.finished %>
      <% actions_as_leader = @user.actions_as_leader %>
      <% events_as_volunteer = @user.events_as_volunteer.upcoming %>

      <% if events_as_volunteer.any? %>
        <% events_as_volunteer.each do |event| %>
          <%= render '/actions/action_entry', event: event %>
        <% end %>
      <% end %>

      <% if actions_as_leader.any? %>
        <h3 class="mt-3"><%= t('user.heading.actionsAsLeader') %></h3>
        <% actions_as_leader.each do |action| %>
          <%= render '/actions/action_entry', action: action %>
        <% end %>
      <% end %>

      <% if past_events.any? %>
        <h3 class="mt-3"><%= t('user.heading.pastActions') %></h3>
        <% past_events.sort_by {|e| e.date}.each do |event| %>
          <%= render '/actions/action_entry', event: event, show_occupancy: false %>
        <% end %>
      <% end %>

      <% if @user.actions_as_volunteer.blank? && @user.actions_as_leader.blank? %>
        <%= own_profile ? t('user.info.youHaveNoActions') : t('user.info.hasNoActions', user: @user.first_name) %>
      <% end %>

      <div>
        <% if own_profile  %>
          <%= link_to user_ical_path(@user.ical_token, @user),
                      data: { turbolinks: false }, class: 'btn btn-primary mt-4 float-right' do %>
            <span class="far fa-calendar-alt"></span>
            <%= t('user.button.exportICal') %>
          <% end %>
        <% end %>
      </div>

    </section>

  </div>
</div>

app/views/users/unsubscribe.erb
<% provide :title, 'Unsubscribe success' %>
<% wrapper_set 'white-box', 'container-small' %>

<h3><%= t('user.heading.unsubscribed') %></h3>
<%= t('user.info.unsubscribed.' + @type.to_s, user: @user.first_name) %>